#!/usr/bin/env python3

import argparse
import getpass
import os
import stat
import subprocess
import tempfile

parser = argparse.ArgumentParser()
parser.add_argument('encfssourcedir', type=str)
args = parser.parse_args()

password = getpass.getpass(prompt='Encfs password (from encfsctl-showcruft-inclear):')

with tempfile.NamedTemporaryFile('w', delete=False) as password_fp:
    st = os.stat(password_fp.name)
    os.chmod(password_fp.name, st.st_mode | stat.S_IEXEC)

    password_fp.write('#!/bin/sh\n')
    password_fp.write('echo "' + password + '"\n')

print(os.path.exists(password_fp.name))

cruft_completed = subprocess.run('encfsctl showcruft ' + args.encfssourcedir, stdout=subprocess.PIPE, shell=True)
assert(cruft_completed.returncode == 0)
for line in cruft_completed.stdout.decode('utf-8').splitlines():
    if line.startswith(args.encfssourcedir) and '.encfs6.xml' not in line:
        pathelements = list(filter(len, line.rsplit(sep=args.encfssourcedir)[1].split('/')))
        for element in pathelements:
            element_completed = subprocess.run('encfsctl decode --extpass="' +
                                               password_fp.name + '" ' + args.encfssourcedir +
                                               ' ' + element, stdout=subprocess.PIPE, shell=True)
            print(element_completed.stdout)

os.remove(password_fp.name)
