#!/usr/bin/perl
#
# The objective of this program is to run as a daemon, awakening fetchmail
# only when the system load is below a nominated value.
#
# TODO:
#  Seems to have a bug where sometimes doesn't come out of sleep.
#
#  Change so that invokes fetchmail directly according to own defined
#  behaviour, passing in own arguments - remove system-wide fetchmail.

use Getopt::Mixed 1.006;
use Sys::CpuLoad;
use Unix::Syslog qw(:macros);  # Syslog macros
use Unix::Syslog qw(:subs);    # Syslog functions
use strict;
use warnings;

use constant DEFAULT_LOAD => 0.5;
use constant DEFAULT_SLEEP => 180;

our $opt_load;
our $opt_sleep;
our $cpuload;

Getopt::Mixed::getOptions("load=f l>load " .
                          "sleep=i s>sleep ");

$opt_load or $opt_load = DEFAULT_LOAD;
$opt_sleep or $opt_sleep = DEFAULT_SLEEP;

openlog("fetchmail-pusher", LOG_PID, LOG_DAEMON);

while(1)
{
    sleep $opt_sleep;

    $cpuload = (Sys::CpuLoad->load())[0];

    if ($cpuload > $opt_load)
    {
        syslog(LOG_NOTICE, "Loaded (%.2f/%.2f) - doing nothing.\n", $cpuload, $opt_load);
    }
    else
    {
        syslog(LOG_INFO, "Unloaded (%.2f/%.2f) - awakening fetchmail.\n", $cpuload, $opt_load);
        system('/etc/init.d/fetchmail awaken')
            and die "Couldn't awaken fetchmail";
    }
};

closelog();
