#!/usr/bin/env python3
#
# Cannot use "fastkml" because of https://github.com/cleder/fastkml/issues/37

import sys
import dateutil.parser
import sqlite3

from lxml import etree
from tqdm import tqdm

tree = etree.parse(sys.argv[1])
root = tree.getroot()

track = root.xpath("//*[local-name() = 'Track']")[0]

coords = []
whens = []

for child in tqdm(track, desc="Parsing XML"):
    if(child.tag.endswith("coord")):
        (lon, lat, alt) = child.text.split()
        coords.append([lon, lat, alt])

    if(child.tag.endswith("when")):
        whens.append(dateutil.parser.parse(child.text).strftime('%s'))

assert(len(coords) == len(whens))

conn = sqlite3.connect(sys.argv[2])
c = conn.cursor()

c.execute("CREATE TABLE IF NOT EXISTS locations (timestamp INTEGER, timestamp_msgrcvd INTEGER, lat REAL, lon REAL, distance REAL, tid TEXT, acc INTEGER, alt INTEGER, batt INTEGER, t TEXT, vac INTEGER)")
conn.commit()

for ((lon, lat, alt), when) in tqdm(zip(coords, whens), desc="Inserting into sqlite3", total=len(coords)):
    c.execute("INSERT INTO locations (timestamp, lon, lat, alt) VALUES(" + when + "," + lon + "," + lat + "," + alt + ")")
    conn.commit()
