#!/bin/sh
#
# $Id$

find | rename $@ -v 's/(Photo|Video) (\d\d)-(\d\d)-(\d\d\d\d) (\d\d) (\d\d) (\d\d)(\.jpg|\.png|\.mov)/${4}-${3}-${2}-${5}-${6}-${7}${8}/'
find | rename $@ -v 's/IMG_(\d\d\d\d)(\d\d)(\d\d)_(\d\d)(\d\d)(\d\d)\.jpg/${1}-${2}-${3}-${4}-${5}-${6}\.jpg/'
find | rename $@ -v 's/VID_(\d\d\d\d)(\d\d)(\d\d)_(\d\d)(\d\d)(\d\d)\.mp4/${1}-${2}-${3}-${4}-${5}-${6}\.mp4/'
